I will write only in english with all I know, so maybe i will make some mistakes.

My goal is build this project with no IA helping me code, just remember me some definitions that i forgot.

# Exploratory Data Analysis

This notebook is an exploratory notebook.

All the csv files can be downloded in this link: https://www.kaggle.com/datasets/ektarr/counter-strike-pro-matches/data

In [16]:
# %%
# 1. imports
import pandas as pd
import numpy as np
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))  # sobe de notebooks/ pra raiz do projeto, onde está src/

from src.dataset import load_dataframe, remove_summary_serie, remove_invalid_bestof, remove_missing_player_id, remove_missing_maps_id

In [1]:
# %%

# 3. cs2 all tiers game file
cs2_all_tier_games_df = load_dataframe("cs2_all_tiers_games.csv")

NameError: name 'load_dataframe' is not defined

In [19]:
# %%

pd.set_option('display.max_columns', None)

In [20]:
print(cs2_all_tier_games_df.columns.to_list())

['match_id', 'game_id', 'tournament', 'team1_id', 'team1', 'team2_id', 'team2', 'score1_match', 'score2_match', 'is_total', 'bestOf', 'score1_game', 'score2_game', 'map_id', 'map_name', 'datetime', 'team1_win', 'games_played', 'team1_player1_id', 'team1_player2_id', 'team1_player3_id', 'team1_player4_id', 'team1_player5_id', 'team2_player1_id', 'team2_player2_id', 'team2_player3_id', 'team2_player4_id', 'team2_player5_id', 'team1_player1', 'team1_player2', 'team1_player3', 'team1_player4', 'team1_player5', 'team2_player1', 'team2_player2', 'team2_player3', 'team2_player4', 'team2_player5', 'team1_player1_kills', 'team1_player1_deaths', 'team1_player1_assists', 'team1_player1_adr', 'team1_player1_kast', 'team1_player1_kddiff', 'team1_player2_kills', 'team1_player2_deaths', 'team1_player2_assists', 'team1_player2_adr', 'team1_player2_kast', 'team1_player2_kddiff', 'team1_player3_kills', 'team1_player3_deaths', 'team1_player3_assists', 'team1_player3_adr', 'team1_player3_kast', 'team1_player3_kddiff', 'team1_player4_kills', 'team1_player4_deaths', 'team1_player4_assists', 'team1_player4_adr', 'team1_player4_kast', 'team1_player4_kddiff', 'team1_player5_kills', 'team1_player5_deaths', 'team1_player5_assists', 'team1_player5_adr', 'team1_player5_kast', 'team1_player5_kddiff', 'team2_player1_kills', 'team2_player1_deaths', 'team2_player1_assists', 'team2_player1_adr', 'team2_player1_kast', 'team2_player1_kddiff', 'team2_player2_kills', 'team2_player2_deaths', 'team2_player2_assists', 'team2_player2_adr', 'team2_player2_kast', 'team2_player2_kddiff', 'team2_player3_kills', 'team2_player3_deaths', 'team2_player3_assists', 'team2_player3_adr', 'team2_player3_kast', 'team2_player3_kddiff', 'team2_player4_kills', 'team2_player4_deaths', 'team2_player4_assists', 'team2_player4_adr', 'team2_player4_kast', 'team2_player4_kddiff', 'team2_player5_kills', 'team2_player5_deaths', 'team2_player5_assists', 'team2_player5_adr', 'team2_player5_kast', 'team2_player5_kddiff']

In [21]:
# %%
stats = ['kills', 'deaths', 'assists', 'adr', 'kast', 'kddiff']

team_stats = [f'team{team}_player{player}_{stat}'
    for team in [1, 2]
    for player in range(1, 6)
    for stat in stats]

other_stats = ['is_total', 'bestOf', 'score1_game', 'score2_game', 'datetime', 'games_played']

do_not_count_summary = cs2_all_tier_games_df[cs2_all_tier_games_df['is_total'] == False]

do_not_count_summary[(team_stats + other_stats)].describe()

,team1_player1_kills,team1_player1_deaths,team1_player1_assists,team1_player1_adr,team1_player1_kast,team1_player1_kddiff,team1_player2_kills,team1_player2_deaths,team1_player2_assists,team1_player2_adr,team1_player2_kast,team1_player2_kddiff,team1_player3_kills,team1_player3_deaths,team1_player3_assists,team1_player3_adr,team1_player3_kast,team1_player3_kddiff,team1_player4_kills,team1_player4_deaths,team1_player4_assists,team1_player4_adr,team1_player4_kast,team1_player4_kddiff,team1_player5_kills,team1_player5_deaths,team1_player5_assists,team1_player5_adr,team1_player5_kast,team1_player5_kddiff,team2_player1_kills,team2_player1_deaths,team2_player1_assists,team2_player1_adr,team2_player1_kast,team2_player1_kddiff,team2_player2_kills,team2_player2_deaths,team2_player2_assists,team2_player2_adr,team2_player2_kast,team2_player2_kddiff,team2_player3_kills,team2_player3_deaths,team2_player3_assists,team2_player3_adr,team2_player3_kast,team2_player3_kddiff,team2_player4_kills,team2_player4_deaths,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff,bestOf,score1_game,score2_game,games_played
count,10502.000000,10502.000000,10502.000000,10502.000000,10502.000000,10502.000000,10379.000000,10379.000000,10379.000000,10379.000000,10379.000000,10379.000000,10417.000000,10417.000000,10417.000000,10417.000000,10417.000000,10417.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10422.000000,10208.000000,10208.000000,10208.000000,10208.000000,10208.000000,10208.000000,10302.000000,10302.000000,10302.000000,10302.000000,10302.000000,10302.000000,10258.000000,10258.000000,10258.000000,10258.000000,10258.000000,10258.000000,10232.000000,10232.000000,10232.000000,10232.000000,10232.000000,10232.000000,10185.000000,10185.000000,10185.000000,10185.000000,10185.000000,10185.000000,10015.000000,10015.000000,10015.000000,10015.000000,10015.000000,10015.000000,10733.000000,10714.000000,10714.000000,10753.000000
mean,14.393544,14.272615,5.335365,73.730623,72.310979,0.120929,14.732344,14.308797,5.071780,74.494402,72.567723,0.423548,14.519439,14.227705,4.980417,72.937919,72.383863,0.291735,14.670984,14.236039,4.959413,73.566811,72.462781,0.434945,14.525960,14.313969,4.957288,73.124500,72.305848,0.211991,14.058047,14.633275,5.140361,72.044914,70.789031,-0.575228,14.257458,14.709008,4.936050,72.471856,70.793040,-0.451550,14.189113,14.551407,4.862588,71.325176,70.809265,-0.362295,14.413157,14.601473,4.876092,72.329023,70.971851,-0.188316,14.325612,14.610384,4.777933,71.918772,70.945821,-0.284773,2.908693,11.132164,10.595016,2.464336
std,5.389827,4.391368,2.901173,19.136220,11.865318,5.925709,5.533744,4.334595,2.724052,19.559383,11.885515,5.991001,5.496580,4.368490,2.692654,19.183392,11.835101,5.929100,5.532127,4.328970,2.750960,19.663042,11.876174,6.053716,5.464664,4.410089,2.692921,19.204962,11.769402,5.981498,5.472361,4.160391,2.867711,18.805100,12.025422,5.869989,5.508049,4.139217,2.745556,18.966045,11.943318,5.865514,5.466661,4.149642,2.731077,18.769915,11.912367,5.808244,5.635179,4.140281,2.671414,19.156301,11.966318,6.002036,5.639804,4.181518,2.715270,18.950446,11.986179,5.962852,0.597432,3.731676,3.983418,0.665124
min,0.000000,1.000000,0.000000,3.900000,7.700000,-20.000000,0.000000,1.000000,0.000000,10.600000,15.400000,-17.000000,1.000000,0.000000,0.000000,12.600000,20.000000,-17.000000,0.000000,2.000000,0.000000,0.400000,17.600000,-18.000000,0.000000,1.000000,0.000000,14.300000,7.700000,-19.000000,1.000000,2.000000,0.000000,14.400000,14.300000,-19.000000,0.000000,1.000000,0.000000,4.800000,13.300000,-20.000000,0.000000,2.000000,0.000000,13.900000,20.000000,-21.000000,1.000000,1.000000,0.000000,15.600000,15.400000,-16.000000,1.000000,1.000000,0.000000,17.800000,20.000000,-22.000000,1.000000,0.000000,0.000000,1.000000
25%,11.000000,12.000000,3.000000,60.300000,65.000000,-4.000000,11.000000,12.000000,3.000000,61.100000,65.200000,-4.000000,11.000000,12.000000,3.000000,59.600000,65.200000,-4.000000,11.000000,12.000000,3.000000,60.100000,65.200000,-4.000000,11.000000,12.000000,3.000000,60.000000,65.000000,-4.000000,10.000000,12.000000,3.000000,59.200000,63.200000,-5.000000,10.000000,12.000000,3.000000,59.300000,63.300000,-5.000000,10.000000,12.000000,3.000000,58.375000,63.200000,-5.000000,11.000000,12.000000,3.000000,59.100000,63.400000,-5.000000,10.000000,12.000000,3.000000,58.750000,63.300000,-5.000000,3.000000,9.000000,8.000000,2.000000
50%,14.000000,14.000000,5.000000,72.900000,72.700000,0.000000,14.000000,14.000000,5.000000,73.200000,73.300000,0.000000,14.000000,14.000000,5.000000,71.900000,73.200000,0.000000,14.000000,14.000000,5.000000,72.400000,72.700000,0.000000,14.000000,14.000000,5.000000,72.100000,72.700000,0.000000,14.000000,15.000000,5.000000,71.000000,71.400000,-1.000000,14.000000,15.000000,5.000000,71.500000,71.400000,-1.000000,14.000000,14.000000,5.000000,70.400000,71.400000,-1.000000,14.000000,14.000000,5.000000,71.400000,71.400000,-1.000000,14.000000,15.000000,4.000000,71.200000,71.400000,-1.000000,3.000000,13.000000,13.000000,3.000000
75%,18.000000,16.000000,7.000000,85.900000,80.000000,4.000000,18.000000,17.000000,7.000000,86.400000,81.000000,5.000000,18.000000,16.000000,7.000000,84.800000,80.000000,4.000000,18.000000,16.000000,7.000000,85.600000,81.000000,5.000000,18.000000,16.000000,7.000000,85.000000,80.000000,4.000000,17.000000,17.000000,7.000000,83.700000,78.900000,3.000000,18.000000,17.000000,7.000000,84.700000,79.200000,4.000000,17.000000,17.000000,6.000000,83.200000,78.900000,4.000000,18.000000,17.000000,6.000000,84.400000,79.200000,4.000000,18.000000,17.000000,6.000000,84.000000,79.200000,4.000000,3.000000,13.000000,13.000000,3.000000
max,55.000000,49.000000,22.000000,164.100000,100.000000,23.000000,58.000000,55.000000,19.000000,179.100000,100.000000,27.000000,58.000000,45.000000,22.000000,163.700000,100.000000,24.000000,56.000000,50.000000,21.000000,161.300000,100.000000,22.000000,47.000000,53.000000,23.000000,165.200000,100.000000,28.000000,67.000000,49.000000,22.000000,184.900000,100.000000,27.000000,50.000000,53.000000,23.000000,186.400000,100.000000,23.000000,47.000000,49.000000,23.000000,167.900000,100.000000,22.000000,53.000000,47.000000,21.000000,165.100000,100.000000,24.000000,50.000000,53.000000,28.000000,174.900000,100.000000,31.000000,5.000000,37.000000,34.000000,5.000000

- I didn't count 'BO' summary rows (where "is_total" == True)
- There's no outliers

In [22]:
#cs2_all_tier_games_df[np.logical_'or'(cs2_all_tier_games_df['team1'] == 294995, cs2_all_tier_games_df['team2_id'] == 294995)]

cs2_all_tier_games_df[(cs2_all_tier_games_df['team1'] == 'Team Vitality') & (cs2_all_tier_games_df['team2'] == 'Team Falcons') & (~ cs2_all_tier_games_df['is_total'])]

,match_id,game_id,tournament,team1_id,team1,team2_id,team2,score1_match,score2_match,is_total,bestOf,score1_game,score2_game,map_id,map_name,datetime,team1_win,games_played,team1_player1_id,team1_player2_id,team1_player3_id,team1_player4_id,team1_player5_id,team2_player1_id,team2_player2_id,team2_player3_id,team2_player4_id,team2_player5_id,team1_player1,team1_player2,team1_player3,team1_player4,team1_player5,team2_player1,team2_player2,team2_player3,team2_player4,team2_player5,team1_player1_kills,team1_player1_deaths,team1_player1_assists,team1_player1_adr,team1_player1_kast,team1_player1_kddiff,team1_player2_kills,team1_player2_deaths,team1_player2_assists,team1_player2_adr,team1_player2_kast,team1_player2_kddiff,team1_player3_kills,team1_player3_deaths,team1_player3_assists,team1_player3_adr,team1_player3_kast,team1_player3_kddiff,team1_player4_kills,team1_player4_deaths,team1_player4_assists,team1_player4_adr,team1_player4_kast,team1_player4_kddiff,team1_player5_kills,team1_player5_deaths,team1_player5_assists,team1_player5_adr,team1_player5_kast,team1_player5_kddiff,team2_player1_kills,team2_player1_deaths,team2_player1_assists,team2_player1_adr,team2_player1_kast,team2_player1_kddiff,team2_player2_kills,team2_player2_deaths,team2_player2_assists,team2_player2_adr,team2_player2_kast,team2_player2_kddiff,team2_player3_kills,team2_player3_deaths,team2_player3_assists,team2_player3_adr,team2_player3_kast,team2_player3_kddiff,team2_player4_kills,team2_player4_deaths,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff
93,7302776,154141.0,IEM Cologne Major 2026,294994,Team Vitality,294995,Team Falcons,1.0,2.0,False,3.0,11.0,13.0,6.0,Dust2,2026-06-19 22:25:00,0,3.0,146.0,1443.0,1549.0,550.0,19.0,26434.0,2041.0,28.0,945.0,26.0,"ropz (Robin Kool), EE","mezii (William Merriman), GB","flameZ (Shahar Shushan), IL","ZywOo (Mathieu Herbaut), FR","apEX (Dan Madesclaire), FR",Kyousuke,"m0NESY (Ilya Osipov), RU","karrigan (Finn Andersen), DK","TeSeS (Rene Madsen), DK","NiKo (Nikola Kovač), BA",19.0,16.0,3.0,84.5,75.0,3.0,20.0,17.0,4.0,82.9,66.7,3.0,11.0,20.0,5.0,57.6,66.7,-9.0,13.0,15.0,6.0,67.8,75.0,-2.0,17.0,17.0,9.0,73.7,66.7,0.0,16.0,17.0,10.0,86.7,87.5,-1.0,23.0,13.0,6.0,82.7,83.3,10.0,15.0,20.0,9.0,76.0,62.5,-5.0,18.0,15.0,7.0,81.8,83.3,3.0,13.0,17.0,6.0,61.2,75.0,-4.0
94,7302776,154140.0,IEM Cologne Major 2026,294994,Team Vitality,294995,Team Falcons,1.0,2.0,False,3.0,13.0,11.0,5.0,Inferno,2026-06-19 22:25:00,0,3.0,146.0,1443.0,1549.0,550.0,19.0,26434.0,2041.0,28.0,945.0,26.0,"ropz (Robin Kool), EE","mezii (William Merriman), GB","flameZ (Shahar Shushan), IL","ZywOo (Mathieu Herbaut), FR","apEX (Dan Madesclaire), FR",Kyousuke,"m0NESY (Ilya Osipov), RU","karrigan (Finn Andersen), DK","TeSeS (Rene Madsen), DK","NiKo (Nikola Kovač), BA",17.0,14.0,5.0,85.0,79.2,3.0,12.0,14.0,2.0,50.5,58.3,-2.0,14.0,17.0,8.0,66.8,75.0,-3.0,26.0,13.0,3.0,108.8,83.3,13.0,10.0,16.0,8.0,58.5,66.7,-6.0,15.0,17.0,7.0,77.5,62.5,-2.0,25.0,14.0,4.0,104.7,79.2,11.0,4.0,17.0,4.0,30.3,62.5,-13.0,12.0,14.0,3.0,43.4,62.5,-2.0,17.0,17.0,7.0,79.8,83.3,0.0
95,7302776,154139.0,IEM Cologne Major 2026,294994,Team Vitality,294995,Team Falcons,1.0,2.0,False,3.0,11.0,13.0,23.0,Anubis,2026-06-19 22:25:00,0,3.0,146.0,1443.0,1549.0,550.0,19.0,26434.0,2041.0,28.0,945.0,26.0,"ropz (Robin Kool), EE","mezii (William Merriman), GB","flameZ (Shahar Shushan), IL","ZywOo (Mathieu Herbaut), FR","apEX (Dan Madesclaire), FR",Kyousuke,"m0NESY (Ilya Osipov), RU","karrigan (Finn Andersen), DK","TeSeS (Rene Madsen), DK","NiKo (Nikola Kovač), BA",16.0,12.0,4.0,71.9,87.5,4.0,12.0,17.0,10.0,81.3,79.2,-5.0,16.0,17.0,3.0,64.4,75.0,-1.0,15.0,14.0,3.0,56.4,66.7,1.0,16.0,16.0,7.0,82.8,62.5,0.0,21.0,16.0,4.0,86.9,83.3,5.0,15.0,13.0,5.0,67.6,58.3,2.0,12.0,18.0,6.0,64.0,62.5,-6.0,13.0,13.0,5.0,74.7,70.8,0.0,15.0,15.0,5.0,48.2,70.8,0.0
1190,7299748,153525.0,IEM Rio 2026,290402,Team Vitality,290403,Team Falcons,1.0,2.0,False,3.0,13.0,6.0,6.0,Dust2,2026-04-15 21:00:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,26434.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Kyousuke,12.0,12.0,6.0,73.7,84.2,0.0,15.0,11.0,7.0,83.6,78.9,4.0,17.0,10.0,6.0,86.5,78.9,7.0,16.0,8.0,3.0,93.4,94.7,8.0,16.0,8.0,0.0,77.6,78.9,8.0,6.0,17.0,6.0,48.0,57.9,-11.0,11.0,15.0,2.0,51.9,47.4,-4.0,8.0,13.0,2.0,54.5,52.6,-5.0,16.0,14.0,2.0,92.0,68.4,2.0,8.0,17.0,5.0,63.9,52.6,-9.0
1193,7299748,153524.0,IEM Rio 2026,290402,Team Vitality,290403,Team Falcons,1.0,2.0,False,3.0,10.0,13.0,8.0,Mirage,2026-04-15 21:00:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,26434.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Kyousuke,13.0,18.0,11.0,79.0,52.2,-5.0,19.0,16.0,2.0,69.0,73.9,3.0,20.0,18.0,5.0,85.4,87.0,2.0,7.0,16.0,7.0,45.9,73.9,-9.0,17.0,13.0,3.0,90.7,69.6,4.0,13.0,15.0,6.0,60.6,78.3,-2.0,10.0,16.0,9.0,54.8,73.9,-6.0,19.0,17.0,3.0,86.3,65.2,2.0,17.0,13.0,7.0,90.9,82.6,4.0,22.0,15.0,2.0,84.3,73.9,7.0
1194,7299748,153526.0,IEM Rio 2026,290402,Team Vitality,290403,Team Falcons,1.0,2.0,False,3.0,14.0,16.0,2.0,Nuke,2026-04-15 21:00:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,26434.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Kyousuke,19.0,26.0,8.0,65.0,70.0,-7.0,19.0,19.0,8.0,71.7,70.0,0.0,21.0,22.0,9.0,80.4,66.7,-1.0,14.0,20.0,7.0,38.5,70.0,-6.0,24.0,21.0,9.0,92.3,63.3,3.0,25.0,20.0,6.0,92.3,83.3,5.0,25.0,16.0,1.0,68.0,70.0,9.0,13.0,21.0,11.0,60.4,73.3,-8.0,26.0,18.0,7.0,89.3,80.0,8.0,19.0,22.0,8.0,73.9,73.3,-3.0
3309,6102910,125106.0,BLAST Bounty Winter 2026,285256,Team Vitality,285257,Team Falcons,1.0,2.0,False,3.0,10.0,13.0,5.0,Inferno,2026-01-24 18:00:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,28237.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Nucleonz,10.0,17.0,9.0,42.4,60.9,-7.0,13.0,17.0,7.0,57.0,47.8,-4.0,16.0,15.0,8.0,86.8,78.3,1.0,16.0,17.0,5.0,77.0,73.9,-1.0,13.0,14.0,3.0,57.2,65.2,-1.0,18.0,13.0,7.0,92.2,73.9,5.0,7.0,13.0,5.0,45.2,73.9,-6.0,22.0,14.0,6.0,95.9,82.6,8.0,20.0,15.0,9.0,80.8,65.2,5.0,13.0,13.0,2.0,49.1,78.3,0.0
3310,6102910,125107.0,BLAST Bounty Winter 2026,285256,Team Vitality,285257,Team Falcons,1.0,2.0,False,3.0,13.0,4.0,23.0,Anubis,2026-01-24 18:00:00,1,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,28237.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Nucleonz,9.0,10.0,10.0,65.1,82.4,-1.0,19.0,8.0,5.0,107.5,82.4,11.0,20.0,11.0,3.0,96.2,88.2,9.0,12.0,11.0,8.0,95.4,82.4,1.0,11.0,11.0,5.0,58.4,82.4,0.0,7.0,15.0,6.0,58.2,52.9,-8.0,7.0,12.0,1.0,27.5,76.5,-5.0,8.0,15.0,8.0,66.2,58.8,-7.0,18.0,14.0,3.0,97.9,82.4,4.0,11.0,15.0,3.0,72.0,52.9,-4.0
3311,6102910,125108.0,BLAST Bounty Winter 2026,285256,Team Vitality,285257,Team Falcons,1.0,2.0,False,3.0,6.0,13.0,8.0,Mirage,2026-01-24 18:00:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,28237.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Nucleonz,9.0,16.0,5.0,71.3,47.4,-7.0,5.0,15.0,6.0,49.8,52.6,-10.0,13.0,15.0,3.0,68.4,57.9,-2.0,11.0,14.0,4.0,62.0,68.4,-3.0,13.0,14.0,1.0,62.3,63.2,-1.0,21.0,9.0,8.0,116.1,84.2,12.0,6.0,11.0,1.0,38.2,68.4,-5.0,11.0,12.0,11.0,73.9,68.4,-1.0,16.0,9.0,2.0,80.4,68.4,7.0,20.0,10.0,4.0,92.8,73.7,10.0
4891,4882088,124399.0,ESL Pro League Season 22,260092,Team Vitality,260093,Team Falcons,3.0,0.0,False,5.0,13.0,5.0,6.0,Dust2,2025-10-12 18:00:00,1,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,26434.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Kyousuke,12.0,10.0,9.0,65.9,83.3,2.0,12.0,10.0,4.0,72.6,66.7,2.0,14.0,11.0,6.0,86.1,83.3,3.0,19.0,10.0,6.0,95.2,88.9,9.0,13.0,11.0,10.0,85.3,83.3,2.0,11.0,13.0,7.0,87.0,61.1,-2.0,7.0,16.0,3.0,46.2,55.6,-9.0,6.0,12.0,2.0,45.7,61.1,-6.0,16.0,14.0,3.0,86.7,72.2,2.0,12.0,15.0,4.0,57.9,77.8,-3.0
4892,4882088,124398.0,ESL Pro League Season 22,260092,Team Vitality,260093,Team Falcons,3.0,0.0,False,5.0,13.0,9.0,3.0,Train,2025-10-12 18:00:00,1,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,26434.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Kyousuke,17.0,15.0,6.0,81.0,63.6,2.0,17.0,9.0,4.0,70.1,77.3,8.0,23.0,14.0,2.0,106.0,81.8,9.0,10.0,12.0,9.0,60.0,68.2,-2.0,14.0,13.0,10.0,90.6,81.8,1.0,19.0,18.0,6.0,103.5,77.3,1.0,10.0,17.0,2.0,49.7,54.5,-7.0,10.0,16.0,1.0,47.3,63.6,-6.0,16.0,14.0,4.0,72.2,77.3,2.0,8.0,16.0,6.0,45.5,72.7,-8.0
4893,4882088,124397.0,ESL Pro League Season 22,260092,Team Vitality,260093,Team Falcons,3.0,0.0,False,5.0,13.0,10.0,5.0,Inferno,2025-10-12 18:00:00,1,3.0,19.0,550.0,1549.0,1443.0,146.0,26.0,945.0,2611.0,2041.0,26434.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",Kyousuke,11.0,16.0,12.0,63.6,78.3,-5.0,13.0,8.0,8.0,53.8,69.6,5.0,25.0,16.0,5.0,112.2,73.9,9.0,12.0,16.0,7.0,61.0,82.6,-4.0,17.0,11.0,5.0,68.3,91.3,6.0,16.0,15.0,10.0,89.1,82.6,1.0,12.0,14.0,4.0,50.0,65.2,-2.0,6.0,18.0,9.0,41.0,60.9,-12.0,19.0,14.0,5.0,76.9,82.6,5.0,14.0,17.0,5.0,68.1,91.3,-3.0
5996,3778076,123906.0,Esports World Cup 2025 по CS2,276278,Team Vitality,276279,Team Falcons,1.0,2.0,False,3.0,13.0,9.0,5.0,Inferno,2025-08-24 10:00:00,1,3.0,19.0,550.0,1549.0,1443.0,146.0,26434.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE",Kyousuke,"NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",16.0,13.0,8.0,88.8,86.4,3.0,9.0,13.0,6.0,56.9,63.6,-4.0,16.0,14.0,5.0,78.9,77.3,2.0,21.0,13.0,8.0,88.3,86.4,8.0,15.0,13.0,3.0,81.8,77.3,2.0,14.0,16.0,4.0,65.9,72.7,-2.0,15.0,16.0,1.0,68.1,59.1,-1.0,8.0,16.0,7.0,58.3,50.0,-8.0,7.0,15.0,4.0,28.3,68.2,-8.0,22.0,14.0,4.0,105.5,86.4,8.0
5997,3778076,123908.0,Esports World Cup 2025 по CS2,276278,Team Vitality,276279,Team Falcons,1.0,2.0,False,3.0,3.0,13.0,2.0,Nuke,2025-08-24 10:00:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,26434.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE",Kyousuke,"NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",7.0,14.0,3.0,74.8,50.0,-7.0,12.0,15.0,4.0,93.0,68.8,-3.0,5.0,14.0,3.0,36.9,56.2,-9.0,10.0,12.0,4.0,75.2,75.0,-2.0,12.0,9.0,0.0,62.8,62.5,3.0,13.0,12.0,5.0,94.3,81.2,1.0,13.0,9.0,4.0,85.1,81.2,4.0,9.0,7.0,3.0,69.9,87.5,2.0,11.0,10.0,3.0,59.4,75.0,1.0,17.0,8.0,4.0,104.1,87.5,9.0
5999,3778076,123907.0,Esports World Cup 2025 по CS2,276278,Team Vitality,276279,Team Falcons,1.0,2.0,False,3.0,3.0,13.0,3.0,Train,2025-08-24 10:00:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,26434.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE",Kyousuke,"NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",2.0,15.0,6.0,55.2,37.5,-13.0,10.0,14.0,0.0,57.7,43.8,-4.0,8.0,13.0,2.0,61.1,43.8,-5.0,5.0,15.0,1.0,45.1,50.0,-10.0,4.0,16.0,4.0,52.3,43.8,-12.0,16.0,11.0,10.0,141.3,100.0,5.0,25.0,6.0,8.0,139.0,93.8,19.0,5.0,4.0,3.0,36.9,100.0,1.0,12.0,5.0,3.0,71.0,93.8,7.0,15.0,3.0,2.0,76.6,87.5,12.0
7356,2956206,123209.0,IEM Dallas 2025,270702,Team Vitality,270703,Team Falcons,2.0,1.0,False,3.0,13.0,11.0,5.0,Inferno,2025-05-25 00:15:00,1,3.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",13.0,16.0,19.0,77.8,79.2,-3.0,22.0,17.0,4.0,83.7,83.3,5.0,17.0,16.0,8.0,80.2,75.0,1.0,19.0,17.0,10.0,86.0,75.0,2.0,13.0,15.0,5.0,64.0,87.5,-2.0,16.0,13.0,4.0,66.4,83.3,3.0,19.0,20.0,5.0,90.6,75.0,-1.0,19.0,15.0,8.0,88.1,83.3,4.0,11.0,20.0,7.0,67.2,75.0,-9.0,15.0,17.0,7.0,64.6,66.7,-2.0
7357,2956206,123208.0,IEM Dallas 2025,270702,Team Vitality,270703,Team Falcons,2.0,1.0,False,3.0,6.0,13.0,3.0,Train,2025-05-25 00:15:00,0,3.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",6.0,15.0,5.0,44.3,42.1,-9.0,12.0,16.0,6.0,66.8,52.6,-4.0,10.0,16.0,8.0,84.8,68.4,-6.0,15.0,13.0,2.0,66.1,68.4,2.0,9.0,16.0,2.0,54.2,52.6,-7.0,17.0,12.0,10.0,114.5,84.2,5.0,14.0,9.0,5.0,76.2,84.2,5.0,15.0,9.0,6.0,81.8,94.7,6.0,8.0,11.0,3.0,53.9,73.7,-3.0,22.0,12.0,3.0,100.5,84.2,10.0
7359,2956206,123207.0,IEM Dallas 2025,270702,Team Vitality,270703,Team Falcons,2.0,1.0,False,3.0,13.0,7.0,6.0,Dust2,2025-05-25 00:15:00,1,3.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",12.0,11.0,8.0,77.5,60.0,1.0,16.0,12.0,4.0,78.8,70.0,4.0,13.0,12.0,2.0,61.5,75.0,1.0,12.0,11.0,4.0,66.6,65.0,1.0,12.0,9.0,8.0,79.1,75.0,3.0,6.0,11.0,2.0,35.1,65.0,-5.0,18.0,14.0,7.0,92.9,75.0,4.0,10.0,13.0,1.0,52.5,75.0,-3.0,13.0,14.0,0.0,69.2,65.0,-1.0,8.0,13.0,4.0,59.0,55.0,-5.0
7879,2691788,122900.0,BLAST Rivals Spring 2025,269222,Team Vitality,269223,Team Falcons,3.0,2.0,False,5.0,9.0,13.0,5.0,Inferno,2025-05-04 17:00:00,0,5.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",12.0,14.0,13.0,77.2,81.8,-2.0,18.0,15.0,2.0,82.0,59.1,3.0,11.0,16.0,2.0,51.6,63.6,-5.0,7.0,16.0,3.0,33.6,59.1,-9.0,16.0,14.0,2.0,84.3,77.3,2.0,13.0,11.0,4.0,71.1,72.7,2.0,14.0,11.0,2.0,61.7,81.8,3.0,14.0,14.0,2.0,71.9,68.2,0.0,10.0,15.0,6.0,61.7,81.8,-5.0,23.0,14.0,6.0,109.5,86.4,9.0
7881,2691788,122902.0,BLAST Rivals Spring 2025,269222,Team Vitality,269223,Team Falcons,3.0,2.0,False,5.0,13.0,6.0,3.0,Train,2025-05-04 17:00:00,1,5.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",10.0,11.0,9.0,54.6,68.4,-1.0,10.0,9.0,5.0,53.1,73.7,1.0,20.0,13.0,7.0,118.5,84.2,7.0,16.0,8.0,4.0,80.7,84.2,8.0,15.0,9.0,2.0,87.8,84.2,6.0,11.0,12.0,2.0,59.4,68.4,-1.0,11.0,16.0,5.0,70.0,57.9,-5.0,9.0,14.0,0.0,47.1,52.6,-5.0,10.0,15.0,6.0,87.9,73.7,-5.0,9.0,14.0,2.0,46.4,63.2,-5.0
7882,2691788,122901.0,BLAST Rivals Spring 2025,269222,Team Vitality,269223,Team Falcons,3.0,2.0,False,5.0,13.0,6.0,6.0,Dust2,2025-05-04 17:00:00,1,5.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",16.0,15.0,10.0,84.3,68.4,1.0,17.0,10.0,5.0,99.5,84.2,7.0,14.0,12.0,2.0,67.0,89.5,2.0,12.0,11.0,8.0,74.1,73.7,1.0,12.0,12.0,2.0,75.0,73.7,0.0,11.0,14.0,7.0,71.9,78.9,-3.0,14.0,14.0,2.0,69.5,84.2,0.0,17.0,15.0,1.0,79.6,73.7,2.0,6.0,15.0,8.0,57.7,68.4,-9.0,12.0,14.0,3.0,66.6,78.9,-2.0
7883,2691788,122904.0,BLAST Rivals Spring 2025,269222,Team Vitality,269223,Team Falcons,3.0,2.0,False,5.0,13.0,8.0,2.0,Nuke,2025-05-04 17:00:00,1,5.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",13.0,14.0,5.0,69.4,71.4,-1.0,20.0,11.0,8.0,96.0,90.5,9.0,12.0,14.0,4.0,61.5,71.4,-2.0,13.0,14.0,6.0,68.9,90.5,-1.0,24.0,10.0,5.0,114.2,90.5,14.0,14.0,16.0,3.0,72.8,71.4,-2.0,8.0,17.0,6.0,60.0,66.7,-9.0,14.0,18.0,3.0,68.2,66.7,-4.0,13.0,15.0,4.0,63.9,57.1,-2.0,13.0,17.0,3.0,73.4,47.6,-4.0
7884,2691788,122903.0,BLAST Rivals Spring 2025,269222,Team Vitality,269223,Team Falcons,3.0,2.0,False,5.0,14.0,16.0,8.0,Mirage,2025-05-04 17:00:00,0,5.0,19.0,550.0,1549.0,1443.0,146.0,41.0,26.0,945.0,2611.0,2041.0,"apEX (Dan Madesclaire), FR","ZywOo (Mathieu Herbaut), FR","flameZ (Shahar Shushan), IL","mezii (William Merriman), GB","ropz (Robin Kool), EE","Magisk (Emil Reif), DK","NiKo (Nikola Kovač), BA","TeSeS (Rene Madsen), DK","kyxsan (Damjan Stoilkovski), MK","m0NESY (Ilya Osipov), RU",13.0,23.0,10.0,46.1,66.7,-10.0,25.0,21.0,9.0,88.9,80.0,4.0,16.0,22.0,7.0,57.4,63.3,-6.0,23.0,25.0,8.0,91.1,80.0,-2.0,24.0,23.0,4.0,88.1,76.7,1.0,16.0,17.0,9.0,58.6,83.3,-1.0,21.0,26.0,12.0,86.3,80.0,-5.0,22.0,23.0,13.0,79.6,80.0,-1.0,20.0,17.0,9.0,69.7,76.7,3.0,35.0,19.0,5.0,101.4,76.7,16.0

In [23]:
# %%

# not missing values

def missing_values_columns(df):
    missing_values_columns = (df.isna().sum() > 0)
    missing_values_columns_df = pd.DataFrame(missing_values_columns, columns= ['result']).reset_index(names= 'match_columns')
    return [match_columns for match_columns, result in zip(missing_values_columns_df['match_columns'], missing_values_columns_df['result']) if result]

In [24]:
# %%

# concat team1_id and team2_id columns
teams = pd.concat([
    cs2_all_tier_games_df[['tournament', 'team1_id']].rename(columns={'team1_id': 'team_id'}),
    cs2_all_tier_games_df[['tournament', 'team2_id']].rename(columns={'team2_id': 'team_id'})
], ignore_index=True)

# Verifying if for each tournament i have a unique team_id
is_team_id_unique = teams.groupby('team_id')['tournament'].nunique().eq(1).all()

print(is_team_id_unique)

True

In [25]:
# %%

# concat team1_id and team2_id columns
team_player = pd.concat([
    cs2_all_tier_games_df[
        ['team1_id',
         'team1_player1_id', 'team1_player2_id', 'team1_player3_id',
         'team1_player4_id', 'team1_player5_id']
    ].rename(columns={
        'team1_id': 'team_id',
        'team1_player1_id': 'player1_id',
        'team1_player2_id': 'player2_id',
        'team1_player3_id': 'player3_id',
        'team1_player4_id': 'player4_id',
        'team1_player5_id': 'player5_id'
    }),

    cs2_all_tier_games_df[
        ['team2_id',
         'team2_player1_id', 'team2_player2_id', 'team2_player3_id',
         'team2_player4_id', 'team2_player5_id']
    ].rename(columns={
        'team2_id': 'team_id',
        'team2_player1_id': 'player1_id',
        'team2_player2_id': 'player2_id',
        'team2_player3_id': 'player3_id',
        'team2_player4_id': 'player4_id',
        'team2_player5_id': 'player5_id'
    })
])

is_player_unique = [
    team_player.groupby('team_id')[f'player{i}_id'].nunique(dropna=False).eq(1).all()
    for i in range(1, 6)
]

print(is_player_unique)

[np.True_, np.True_, np.True_, np.True_, np.True_]

In [26]:
# %%

# is there bias in 'team1_win'?

do_not_count_summary['team1_win'].value_counts(normalize=True)

team1_win
1    0.536036
0    0.463964
Name: proportion, dtype: float64

- There's no bias. It is well distributed

In [27]:
# %%

cs2_all_tier_games_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20676 entries, 0 to 20675
Data columns (total 98 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   match_id               20676 non-null  int64
 1   game_id                15926 non-null  float64
 2   tournament             20676 non-null  str
 3   team1_id               20676 non-null  int64
 4   team1                  20675 non-null  str
 5   team2_id               20676 non-null  int64
 6   team2                  20675 non-null  str
 7   score1_match           20675 non-null  float64
 8   score2_match           20675 non-null  float64
 9   is_total               20676 non-null  bool
 10  bestOf                 20540 non-null  float64
 11  score1_game            13599 non-null  float64
 12  score2_game            13599 non-null  float64
 13  map_id                 13550 non-null  float64
 14  map_name               13550 non-null  str
 15  datetime               20676 non-null  str
 16  team1_win              20676 non-null  int64
 17  games_played           20675 non-null  float64
 18  team1_player1_id       19862 non-null  float64
 19  team1_player2_id       19668 non-null  float64
 20  team1_player3_id       19658 non-null  float64
 21  team1_player4_id       19634 non-null  float64
 22  team1_player5_id       19215 non-null  float64
 23  team2_player1_id       19313 non-null  float64
 24  team2_player2_id       19125 non-null  float64
 25  team2_player3_id       19103 non-null  float64
 26  team2_player4_id       18998 non-null  float64
 27  team2_player5_id       18715 non-null  float64
 28  team1_player1          15544 non-null  str
 29  team1_player2          15359 non-null  str
 30  team1_player3          15413 non-null  str
 31  team1_player4          15427 non-null  str
 32  team1_player5          15109 non-null  str
 33  team2_player1          15244 non-null  str
 34  team2_player2          15173 non-null  str
 35  team2_player3          15141 non-null  str
 36  team2_player4          15067 non-null  str
 37  team2_player5          14808 non-null  str
 38  team1_player1_kills    15544 non-null  float64
 39  team1_player1_deaths   15544 non-null  float64
 40  team1_player1_assists  15544 non-null  float64
 41  team1_player1_adr      15544 non-null  float64
 42  team1_player1_kast     15544 non-null  float64
 43  team1_player1_kddiff   15544 non-null  float64
 44  team1_player2_kills    15359 non-null  float64
 45  team1_player2_deaths   15359 non-null  float64
 46  team1_player2_assists  15359 non-null  float64
 47  team1_player2_adr      15359 non-null  float64
 48  team1_player2_kast     15359 non-null  float64
 49  team1_player2_kddiff   15359 non-null  float64
 50  team1_player3_kills    15413 non-null  float64
 51  team1_player3_deaths   15413 non-null  float64
 52  team1_player3_assists  15413 non-null  float64
 53  team1_player3_adr      15413 non-null  float64
 54  team1_player3_kast     15413 non-null  float64
 55  team1_player3_kddiff   15413 non-null  float64
 56  team1_player4_kills    15427 non-null  float64
 57  team1_player4_deaths   15427 non-null  float64
 58  team1_player4_assists  15427 non-null  float64
 59  team1_player4_adr      15427 non-null  float64
 60  team1_player4_kast     15427 non-null  float64
 61  team1_player4_kddiff   15427 non-null  float64
 62  team1_player5_kills    15109 non-null  float64
 63  team1_player5_deaths   15109 non-null  float64
 64  team1_player5_assists  15109 non-null  float64
 65  team1_player5_adr      15109 non-null  float64
 66  team1_player5_kast     15109 non-null  float64
 67  team1_player5_kddiff   15109 non-null  float64
 68  team2_player1_kills    15244 non-null  float64
 69  team2_player1_deaths   15244 non-null  float64
 70  team2_player1_assists  15244 non-null  float64
 71  team2_player1_adr      15244 non-null  float64
 72  team2_player1_kast     15244 non-null  float64
 73  team2_player1_kddiff   15244 non-null  float64
 74  team2_player2_kills    15173 non-null  float64
 75  team2_player2_deaths   15173 non-null  float64
 76  team2_player2_assists  15173 non-null  float64
 77  team2_player2_adr      15173 non-null  float64
 78  team2_player2_kast     15173 non-null  float64
 79  team2_player2_kddiff   15173 non-null  float64
 80  team2_player3_kills    15141 non-null  float64
 81  team2_player3_deaths   15141 non-null  float64
 82  team2_player3_assists  15141 non-null  float64
 83  team2_player3_adr      15141 non-null  float64
 84  team2_player3_kast     15141 non-null  float64
 85  team2_player3_kddiff   15141 non-null  float64
 86  team2_player4_kills    15067 non-null  float64
 87  team2_player4_deaths   15067 non-null  float64
 88  team2_player4_assists  15067 non-null  float64
 89  team2_player4_adr      15067 non-null  float64
 90  team2_player4_kast     15067 non-null  float64
 91  team2_player4_kddiff   15067 non-null  float64
 92  team2_player5_kills    14808 non-null  float64
 93  team2_player5_deaths   14808 non-null  float64
 94  team2_player5_assists  14808 non-null  float64
 95  team2_player5_adr      14808 non-null  float64
 96  team2_player5_kast     14808 non-null  float64
 97  team2_player5_kddiff   14808 non-null  float64
dtypes: bool(1), float64(78), int64(4), str(15)
memory usage: 15.3 MB

In [28]:
# %%

# best of 1 is unpredictable?

cs2_all_tier_games_df['score_diff'] = (cs2_all_tier_games_df['score1_game'] - cs2_all_tier_games_df['score2_game']).abs()

cs2_all_tier_games_df[cs2_all_tier_games_df['is_total'] == False].groupby('bestOf')['score_diff'].agg(['mean', 'std'])

            mean       std
bestOf
1.0     5.510989  2.841990
3.0     5.295001  2.772444
5.0     5.195918  2.687704

In [35]:
cs2_all_tier_games_df[cs2_all_tier_games_df['match_id'] == 557626]

,match_id,game_id,tournament,team1_id,team1,team2_id,team2,score1_match,score2_match,is_total,bestOf,score1_game,score2_game,map_id,map_name,datetime,team1_win,games_played,team1_player1_id,team1_player2_id,team1_player3_id,team1_player4_id,team1_player5_id,team2_player1_id,team2_player2_id,team2_player3_id,team2_player4_id,team2_player5_id,team1_player1,team1_player2,team1_player3,team1_player4,team1_player5,team2_player1,team2_player2,team2_player3,team2_player4,team2_player5,team1_player1_kills,team1_player1_deaths,team1_player1_assists,team1_player1_adr,team1_player1_kast,team1_player1_kddiff,team1_player2_kills,team1_player2_deaths,team1_player2_assists,team1_player2_adr,team1_player2_kast,team1_player2_kddiff,team1_player3_kills,team1_player3_deaths,team1_player3_assists,team1_player3_adr,team1_player3_kast,team1_player3_kddiff,team1_player4_kills,team1_player4_deaths,team1_player4_assists,team1_player4_adr,team1_player4_kast,team1_player4_kddiff,team1_player5_kills,team1_player5_deaths,team1_player5_assists,team1_player5_adr,team1_player5_kast,team1_player5_kddiff,team2_player1_kills,team2_player1_deaths,team2_player1_assists,team2_player1_adr,team2_player1_kast,team2_player1_kddiff,team2_player2_kills,team2_player2_deaths,team2_player2_assists,team2_player2_adr,team2_player2_kast,team2_player2_kddiff,team2_player3_kills,team2_player3_deaths,team2_player3_assists,team2_player3_adr,team2_player3_kast,team2_player3_kddiff,team2_player4_kills,team2_player4_deaths,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff,score_diff
20526,557626,115878.0,ESL Challenger League Season 46 — Europe,233295,ORKS,233296,IKLA,1.0,2.0,False,3.0,10.0,13.0,8.0,Mirage,2023-10-25 20:30:00,0,3.0,3233.0,3321.0,4236.0,714.0,198.0,5298.0,258.0,4382.0,144.0,1404.0,"OLIMP (Patryk Woźniak ), PL","sNx (Rafal Snopek), PL",NaN,NaN,NaN,"Kvem (Vladislav Korol), UA","MICHU (Michał Müller), PL","xicoz (Zoran Markovski), MK",NaN,"Topa (Alexey Topchienko), UA",18.0,16.0,7.0,79.6,60.9,2.0,15.0,17.0,5.0,73.7,78.3,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,13.0,3.0,89.7,65.2,7.0,29.0,11.0,4.0,120.7,82.6,18.0,5.0,16.0,7.0,39.2,73.9,-11.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,17.0,5.0,70.7,65.2,-2.0,3.0
20527,557626,-115878.0,ESL Challenger League Season 46 — Europe,233295,ORKS,233296,IKLA,1.0,2.0,True,3.0,NaN,NaN,NaN,NaN,2023-10-25 20:30:00,0,3.0,3233.0,3321.0,4236.0,714.0,198.0,5298.0,258.0,4382.0,144.0,1404.0,"OLIMP (Patryk Woźniak ), PL","sNx (Rafal Snopek), PL",NaN,NaN,NaN,"Kvem (Vladislav Korol), UA","MICHU (Michał Müller), PL","xicoz (Zoran Markovski), MK",NaN,"Topa (Alexey Topchienko), UA",51.0,43.0,19.0,99.7,68.5,8.0,44.0,46.0,13.0,73.9,67.1,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,40.0,13.0,112.3,73.3,25.0,61.0,37.0,10.0,97.4,73.8,24.0,29.0,42.0,15.0,56.4,70.9,-13.0,NaN,NaN,NaN,NaN,NaN,NaN,39.0,41.0,16.0,69.6,71.7,-2.0,NaN
20528,557626,115877.0,ESL Challenger League Season 46 — Europe,233295,ORKS,233296,IKLA,1.0,2.0,False,3.0,13.0,8.0,2.0,Nuke,2023-10-25 20:30:00,1,3.0,3233.0,3321.0,4236.0,714.0,198.0,5298.0,258.0,4382.0,144.0,1404.0,"OLIMP (Patryk Woźniak ), PL","sNx (Rafal Snopek), PL",NaN,NaN,NaN,"Kvem (Vladislav Korol), UA","MICHU (Michał Müller), PL","xicoz (Zoran Markovski), MK",NaN,"Topa (Alexey Topchienko), UA",24.0,12.0,4.0,131.5,66.7,12.0,15.0,15.0,4.0,72.8,61.9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,16.0,5.0,128.1,71.4,7.0,18.0,13.0,1.0,78.8,66.7,5.0,13.0,14.0,1.0,57.8,66.7,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,15.0,6.0,65.5,66.7,-6.0,5.0
20529,557626,115874.0,ESL Challenger League Season 46 — Europe,233295,ORKS,233296,IKLA,1.0,2.0,False,3.0,5.0,13.0,24.0,Ancient,2023-10-25 20:30:00,0,3.0,3233.0,3321.0,4236.0,714.0,198.0,5298.0,258.0,4382.0,144.0,1404.0,"OLIMP (Patryk Woźniak ), PL","sNx (Rafal Snopek), PL",NaN,NaN,NaN,"Kvem (Vladislav Korol), UA","MICHU (Michał Müller), PL","xicoz (Zoran Markovski), MK",NaN,"Topa (Alexey Topchienko), UA",9.0,15.0,8.0,88.1,77.8,-6.0,14.0,14.0,4.0,75.3,61.1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,11.0,5.0,119.2,83.3,11.0,14.0,13.0,5.0,92.7,72.2,1.0,11.0,12.0,7.0,72.2,72.2,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,9.0,5.0,72.6,83.3,6.0,8.0